CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    transaction_ref VARCHAR(255),
    mti VARCHAR(10),
    status VARCHAR(50),
    response_code VARCHAR(10),
    response_description VARCHAR(255),
    processing_time_ms BIGINT,
    error_message VARCHAR(255),
    request_fields CLOB,
    response_fields CLOB
);

CREATE INDEX
idx_transactions_transaction_ref ON transactions (transaction_ref);
CREATE INDEX idx_created_at ON transactions (created_at);
CREATE INDEX idx_transactions_mti ON transactions (mti);